* Building from git repo

After downloading need to re-run the setup to download electron etc.

lein descjop-init
lein descjop-externs

The second one of these will fail when there are any events or subscriptions that have names starting with a double colon. At the moment, these are the ones:

| anh-front.core  | ::events/initialize-db  |
| anh-front.views | ::subs/name             |
|                 | ::subs/projects         |

Removing one of the colons, running lein descjop-externs and then replacing the colons works.

* Debugging assistants
** re-frisk
NOTE Using this stops the re-frame template from running, ie lein new re-frame throws an error.

This seems to work. Added [lein-re-frisk "0.5.5"] to ~/.lein/profiles.clj in the :user :plugins section.
Added [re-frisk-remote.core] to the requires in anh-front.core, and called (enable-re-frisk-remote!) in init! as below:
#+BEGIN_SRC clojure
(ns anh-front.core
  (:require  [reagent.core :as reagent :refer [atom]]
             [re-frame.core :as re-frame]
             [anh-front.events :as events]
             [anh-front.views :as views]
             [anh-front.config :as config]
             [re-frisk-remote.core :refer [enable-re-frisk-remote!]]))

(defn mount-root [setting]
  (re-frame/clear-subscription-cache!)
  (reagent/render [views/main-panel]
                  (.getElementById js/document "app")))

(defn init! [setting]
  (re-frame/dispatch-sync [::events/initialize-db])
  (enable-re-frisk-remote!)
  (mount-root setting))
#+END_SRC
Then run the re-frisk server with lein re-frisk and the electron executable and go to localhost:4567 to see the re-frisk data. The server doesn't seem to like being run in the background which is a pain in the arse, but workable.

** js console
Nice and easy access to the re-frame database using this command:
#+BEGIN_SRC javascript
window.re_frame.db.app_db.state
#+END_SRC
** in repl
re-frame.db/app-db shows the contents of db, but also gives an error message.?!? Plus emacs doesn't like the volume of data, and the error means it can't be dereferenced and filtered to limit the amount of data returned. re-frame-demo project doesn't suffer from this. Reverting re-frame to version "0.10.4" fixed this. But only temporarily. What seems to work is changing the version, re-running lein descjop-externs and restarting the repls.
** re-frame-10x
Works fine when included from the re-frame template but not so easy to add by hand.

Using master branch from commit a52a0d1e83b278fd2129948c7334d9b8b3e33581 I get these warnings when running the cljsbuild:
#+BEGIN_SRC shell
(master) working: lein rebuild
Compiling ClojureScript...
Compiling "app/dev/js/main.js" from ["src"]...
WARNING: Use of undeclared Var devtools.formatters.core/header-api-call at line 112 app/dev/js/out_main/day8/re_frame_10x/view/components.cljs
WARNING: Use of undeclared Var devtools.formatters.core/body-api-call at line 115 app/dev/js/out_main/day8/re_frame_10x/view/components.cljs
WARNING: Use of undeclared Var devtools.formatters.core/has-body-api-call at line 118 app/dev/js/out_main/day8/re_frame_10x/view/components.cljs
WARNING: Use of undeclared Var re-frame.subs/kind at line 26 app/dev/js/out_main/day8/re_frame_10x/view/parts.cljs
WARNING: Use of undeclared Var re-frame.fx/kind at line 28 app/dev/js/out_main/day8/re_frame_10x/view/parts.cljs
WARNING: Use of undeclared Var re-frame.cofx/kind at line 30 app/dev/js/out_main/day8/re_frame_10x/view/parts.cljs
Successfully compiled "app/dev/js/main.js" in 28.472 seconds.
#+END_SRC
Get this error message when trying to start electron:
#+BEGIN_SRC shell
(master) working: ./electron/Electron.app/Contents/MacOS/Electron app/dev
App threw an error during load
ReferenceError: document is not defined
    at day8$re_frame_10x$inject_devtools_BANG_ (/Users/iain/Code/Clojure/Descjop/working/app/dev/js/out_main/day8/re_frame_10x.js:435:56)
    at Object.<anonymous> (/Users/iain/Code/Clojure/Descjop/working/app/dev/js/out_main/day8/re_frame_10x/preload.js:12:41)
    at Object.<anonymous> (/Users/iain/Code/Clojure/Descjop/working/app/dev/js/out_main/day8/re_frame_10x/preload.js:16:3)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)

#+END_SRC
Updating to re-frame-10x 0.2.1-SNAPSHOT gets reid of the warnings but not the errors on electron startup.
